- hosts: "{{ ec2_ip }}"
  become: yes
  vars:
    ansible_user: ubuntu
  tasks:
    - name: "Include splunk_otel_collector"
      include_role:
        name: "signalfx.splunk_otel_collector.collector"
      vars:
        splunk_access_token: dYkDpF0-EOaoSnGn2FCrHg
        splunk_realm: us1
        splunk_otel_collector_config: /etc/otel/collector/agent_config.yaml
        install_splunk_otel_auto_instrumentation: yes

    - name: Copiar script de instalación
      copy:
        src: ../install_docker.sh
        dest: /tmp/install_docker.sh
        mode: "0755"

    - name: Ejecutar el script
      shell: /tmp/install_docker.sh

    - name: Iniciar Docker
      service:
        name: docker
        state: started
        enabled: true

    - name: Pull de la imagen
      shell: "docker pull {{ image_name }}:{{ image_tag }}"

    - name: Correr el contenedor
      shell: |
        docker stop flaskapp || true
        docker rm flaskapp || true
        docker run -d --name flaskapp -p 5000:5000 \
          -e DB_HOST={{ db_host }} \
          -e DB_NAME={{ db_name }} \
          -e DB_USER={{ db_user }} \
          -e DB_PASSWORD={{ db_password }} \
          -e FLASK_APP=app.py \
          {{ image_name }}:{{ image_tag }}

    - name: Esperar a que el contenedor arranque
      wait_for:
        host: "{{ ec2_ip }}"
        port: 5000
        delay: 3
        timeout: 30

    - name: Crear directorios para migraciones
      shell: docker exec flaskapp mkdir -p /app/migrations/versions

    - name: Ejecutar flask db upgrade dentro del contenedor
      shell: docker exec flaskapp flask db upgrade
